export enum ActionTypes {
    SET_CURRENT_TRACK,
    CLEAR_AND_SET_LOADED_TRACKS,
    SET_LOADED_TRACKS,
    SET_LOADED_TRACKS_PENDING,
    SET_LOADED_TRACKS_ERROR,
    SET_QUERY_LIMIT,
    SET_QUERY_OFFSET,
    SET_QUERY_ORDER,
    SET_QUERY_TYPE,
    SET_QUERY_BOOST,
    SET_QUERY_TAG,
    SET_PROGRESS_PENDING
}